name: Latest YouTube Videos
on:
  schedule:
    # Runs every hour, on the hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UC-pPnuhjYYfg7Y2cqpSL3rA"
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/"
          date_format: "yyyy.mm.dd"
          template: '<table><tr><td><a href="$url"><img width="150px" src="https://i.ytimg.com/vi/$videoId/mqdefault.jpg"></a></td>$newline<td width="300"><a href="$url">$title</a><br/>$date</td></tr></table>$newline'
          max_post_count: 3
